"""added is_active field in author

Revision ID: 607906c3ac56
Revises: e93833811e7b
Create Date: 2024-07-05 13:13:57.719485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607906c3ac56'
down_revision: Union[str, None] = 'e93833811e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', schema='public', type_='foreignkey')
    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('authors', 'is_active')
    # ### end Alembic commands ###
