"""Initial migration

Revision ID: e93833811e7b
Revises: 
Create Date: 2024-07-03 12:27:30.497209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93833811e7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_authors_id'), 'authors', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_authors_name'), 'authors', ['name'], unique=False, schema='public')
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.authors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_books_id'), 'books', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_books_title'), 'books', ['title'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_books_title'), table_name='books', schema='public')
    op.drop_index(op.f('ix_public_books_id'), table_name='books', schema='public')
    op.drop_table('books', schema='public')
    op.drop_index(op.f('ix_public_authors_name'), table_name='authors', schema='public')
    op.drop_index(op.f('ix_public_authors_id'), table_name='authors', schema='public')
    op.drop_table('authors', schema='public')
    # ### end Alembic commands ###
